version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "1024:80"
    restart: "always"
    environment:
      - TZ=Asia/Tokyo

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "1026:8000"
    restart: "always"
    environment:
      - PYTHONPATH=/app
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native
    restart: "always"
    volumes:
      - ./database/clickhouse/config/user.xml:/etc/clickhouse-server/users.d/default-user.xml:ro
      - ./database/clickhouse/config/custom_config.xml:/etc/clickhouse-server/config.d/custom_config.xml:ro

volumes:
  clickhouse_data:
