version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "1024:80"
    restart: "always"
#   networks:
#     - app-network

#   backend:
#     build:
#       context: ./backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - clickhouse
#     environment:
#       - CLICKHOUSE_HOST=clickhouse
#       - CLICKHOUSE_PORT=8123
#     networks:
#       - app-network

#   clickhouse:
#     image: clickhouse/clickhouse-server:latest
#     ports:
#       - "8123:8123"  # HTTP
#       - "9000:9000"  # Native
#     volumes:
#       - clickhouse_data:/var/lib/clickhouse
#     networks:
#       - app-network

# volumes:
#   clickhouse_data:

# networks:
#   app-network:
#     driver: bridge