version: '3.8'

services:
  client-dev:
    profiles: ["dev"]
    build:
      context: ./client
      target: dev
    volumes: 
      - ./client:/app
      - /app/node_modules
    ports:
      - "1024:8080"
    restart: "always"
    environment:
      - TZ=Asia/Tokyo
  client-prod:
    profiles: ["prod"]
    build:
      context: ./client
      target: prod
    ports:
      - "1024:80"
    restart: "always"
    environment:
      - TZ=Asia/Tokyo

  server-dev:
    profiles: ["dev"]
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/app
    ports:
      - "1026:8000"
    restart: "always"
    environment:
      - PYTHONPATH=/app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=box_score_arc
      - DB_USER=box_score_arc_user
      - DB_PASSWORD=box_score_arc_password
    depends_on:
      - clickhouse
      - postgres
  server-prod:
    profiles: ["prod"]
    build:
      context: ./server
      target: prod
    ports:
      - "1026:8000"
    restart: "always"
    environment:
      - PYTHONPATH=/app
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=box_score_arc
      - DB_USER=box_score_arc_user
      - DB_PASSWORD=box_score_arc_password
    depends_on:
      - clickhouse
      - postgres

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native
    restart: "always"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./database/clickhouse/config/user.xml:/etc/clickhouse-server/users.d/default-user.xml:ro
      - ./database/clickhouse/config/custom_config.xml:/etc/clickhouse-server/config.d/custom_config.xml:ro
  
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      - POSTGRES_DB=box_score_arc
      - POSTGRES_USER=box_score_arc_user
      - POSTGRES_PASSWORD=box_score_arc_password
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  clickhouse_data:
    name: clickhouse_data 
  postgresql_data:
